# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom')),
                ('sexe', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sexe')),
                ('document', models.FileField(null=True, upload_to='photos/', verbose_name='Photo')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de Naissance')),
                ('lieu_naissance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu')),
                ('pere', models.CharField(blank=True, max_length=255, null=True, verbose_name='Noms et Prénoms du Père')),
                ('mere', models.CharField(blank=True, max_length=255, null=True, verbose_name='Noms et Prénoms de la Mère')),
                ('profession', models.CharField(blank=True, max_length=255, null=True, verbose_name='Profession')),
                ('statut', models.CharField(blank=True, max_length=255, null=True, verbose_name='Statut Matrimonial')),
                ('conjoint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Noms et Prénoms conjoint(e)')),
                ('nbre_enfants', models.CharField(blank=True, max_length=255, null=True, verbose_name="Nombre d'enfants")),
                ('pays_origine', models.CharField(blank=True, max_length=255, null=True, verbose_name="Pays d'origine")),
                ('ville_origine', models.CharField(blank=True, max_length=255, null=True, verbose_name="Ville d'origine")),
                ('ville_residence', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ville de Résidence')),
                ('lieu_residence', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de Résidence')),
                ('nationalite', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nationalité')),
                ('cni', models.CharField(blank=True, max_length=255, null=True, verbose_name='Num. CNI')),
                ('cni_delivre_par', models.CharField(blank=True, max_length=255, null=True, verbose_name='Délivré Par')),
                ('date_cni', models.DateField(blank=True, null=True, verbose_name='Date de Délivrance')),
                ('passport', models.CharField(blank=True, max_length=255, null=True, verbose_name='Num. Passeport')),
                ('passp_delivre_par', models.CharField(blank=True, max_length=255, null=True, verbose_name='Délivré Par')),
                ('date_passp', models.DateField(blank=True, null=True, verbose_name='Date de Délivrance')),
                ('date_arr_gab', models.DateField(blank=True, null=True, verbose_name="Date d'arrivée au GABON")),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
