# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 14:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plateforme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='client',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='cni',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Num. CNI'),
        ),
        migrations.AddField(
            model_name='client',
            name='cni_delivre_par',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Délivré Par'),
        ),
        migrations.AddField(
            model_name='client',
            name='conjoint',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Noms et Prénoms conjoint(e)'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_arr_gab',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'arrivée au GABON"),
        ),
        migrations.AddField(
            model_name='client',
            name='date_cni',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Délivrance'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Naissance'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_passp',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Délivrance'),
        ),
        migrations.AddField(
            model_name='client',
            name='lieu_naissance',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='client',
            name='lieu_residence',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de Résidence'),
        ),
        migrations.AddField(
            model_name='client',
            name='mere',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Noms et Prénoms de la Mère'),
        ),
        migrations.AddField(
            model_name='client',
            name='nationalite',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='client',
            name='nbre_enfants',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nombre d'enfants"),
        ),
        migrations.AddField(
            model_name='client',
            name='nom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='client',
            name='passp_delivre_par',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Délivré Par'),
        ),
        migrations.AddField(
            model_name='client',
            name='passport',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Num. Passeport'),
        ),
        migrations.AddField(
            model_name='client',
            name='pays_origine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Pays d'origine"),
        ),
        migrations.AddField(
            model_name='client',
            name='pere',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Noms et Prénoms du Père'),
        ),
        migrations.AddField(
            model_name='client',
            name='prenom',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='client',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profession'),
        ),
        migrations.AddField(
            model_name='client',
            name='sexe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sexe'),
        ),
        migrations.AddField(
            model_name='client',
            name='statut',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Statut Matrimonial'),
        ),
        migrations.AddField(
            model_name='client',
            name='ville_origine',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ville d'origine"),
        ),
        migrations.AddField(
            model_name='client',
            name='ville_residence',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ville de Résidence'),
        ),
        migrations.AlterField(
            model_name='client',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='photos/', verbose_name='Photo'),
        ),
    ]
